/* ISC license. */

/* Generated by: ./configure --prefix=/ --with-sysdeps=/home/scl/learning/buildroot/buildroot-2024.02.8/output/host/arm-buildroot-linux-gnueabi/sysroot/lib/skalibs/sysdeps --with-include=/home/scl/learning/buildroot/buildroot-2024.02.8/output/host/arm-buildroot-linux-gnueabi/sysroot/include --with-dynlib=/home/scl/learning/buildroot/buildroot-2024.02.8/output/host/arm-buildroot-linux-gnueabi/sysroot/lib --with-lib=/home/scl/learning/buildroot/buildroot-2024.02.8/output/host/arm-buildroot-linux-gnueabi/sysroot/lib/skalibs --disable-allstatic --disable-static --enable-shared */

#ifndef MDEVD_CONFIG_H
#define MDEVD_CONFIG_H

#define MDEVD_VERSION "0.1.6.0"
#define MDEVD_BINPREFIX ""
#define MDEVD_EXTBINPREFIX ""
#define MDEVD_LIBEXECPREFIX "/libexec/"

#endif
